--------------------------------------------------------
-- Archivo creado  - viernes-agosto-24-2012   
--------------------------------------------------------
REM INSERTING into REVELACIONES.REV_CODIGO_FECU
SET DEFINE OFF;
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5100000','TOTAL ACTIVO','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5110000','TOTAL INVERSIONES FINANCIERAS','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5111000','Efectivo y Efectivo Equivalente','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5112000','Activos Financieros a Valor Razonable','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5113000','Activos Financieros a Costo Amortizado','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5114000','Préstamos','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5114100','Avance Tenedores de Pólizas','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5114200','Préstamos Otorgados','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5115000','Inversiones Seguros Cuenta Única de Inversión (CUI)','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5116000','Participaciones en Entidades del Grupo','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5116100','Participaciones en Empresas Subsidiarias (Filiales)','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5116200','Participaciones en Empresas Asociadas (Coligadas)','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5120000','TOTAL INVERSIONES INMOBILIARIAS','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5121000','Propiedades de Inversión','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5122000','Cuentas por Cobrar Leasing','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5123000','Propiedades, Muebles y Equipos de Uso Propio','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5123100','Propiedades de Uso Propio','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5123200','Muebles y Equipos de Uso Propio','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5130000','ACTIVOS NO CORRIENTES MANTENIDOS PARA LA VENTA','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5140000','TOTAL CUENTAS DE SEGURO','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5141000','Cuentas por Cobrar de Seguros','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5141100','Cuentas por Cobrar Asegurados','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5141200','Deudores por Operaciones de Reaseguro','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5141210','Siniestros por Cobrar a Reaseguradores','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5141220','Primas por Cobrar Reaseguro Aceptado','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5141230','Activo por Reaseguro No Proporcional','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5141240','Otros Deudores por Operaciones de Reaseguro','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5141300','Deudores por Operaciones de Coaseguro','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5141310','Primas por Cobrar por Operaciones de Coaseguro','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5141320','Siniestros por Cobrar por Operaciones de Coaseguro','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5142000','Participación del Reaseguro en las Reservas Técnicas','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5142100','Participación del Reaseguro en la Reserva Riesgos en Curso','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5142200','Participación del Reaseguro en las Reservas Seguros Previsionales','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5142210','Participación del Reaseguro en la Reserva Rentas Vitalicias','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5142220','Participación del Reaseguro en la Reserva Seguro Invalidez y Sobrevivencia','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5142300','Participación del Reaseguro en la Reserva Matemática','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5142400','Participación del Reaseguro en la Reserva Rentas Privadas','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5142500','Participación del Reaseguro en la Reserva de Siniestros','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5142600','Participación del Reaseguro en la Reserva Catastrófica de Terremoto','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5142700','Participación del Reaseguro en la Reserva de Insuficiencia de Primas','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5142800','Participación del Reaseguro en las Otras Reservas Técnicas','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5150000','OTROS ACTIVOS','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5151000','Intangibles','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5151100','Goodwill','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5151200','Activos Intagibles Distintos a Goodwill','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5152000','Impuestos por Cobrar','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5152100','Cuenta por Cobrar por Impuestos Corrientes','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5152200','Activo por Impuestos Diferidos','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5153000','Otros Activos','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5153100','Deudas del Personal','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5153200','Cuentas por Cobrar Intermediarios','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5153300','Deudores Relacionados','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5153400','Gastos Anticipados','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5153500','Otros Activos','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5200000','TOTAL PASIVOS Y PATRIMONIO (B+C)','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5210000','TOTAL PASIVOS','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5211000','PASIVOS FINANCIEROS','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5212000','PASIVOS NO CORRIENTES MANTENIDOS PARA LA VENTA','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5213000','TOTAL CUENTAS DE SEGUROS','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5213100','Reservas Técnicas','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5213110','Reserva Riesgos en Curso','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5213120','Reservas Seguros Previsionales','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5213121','Reserva Rentas Vitalicias','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5213122','Reserva Seguro Invalidez y Sobrevivencia','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5213130','Reserva Matemática','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5213140','Reserva Valor del Fondo','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5213150','Reserva Rentas Privadas','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5213160','Reserva de Siniestros','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5213170','Reserva Catastrófica Terremoto','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5213180','Reserva de Insuficiencia de Primas','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5213190','Otras Reservas Técnicas','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5213200','Deudas por Operaciones de Seguro','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5213210','Deudas con Asegurados','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5213220','Deudas por Operaciones Reaseguro','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5213230','Deudas por Operaciones por Coaseguro','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5213231','Primas por Pagar por Operaciones de Coaseguro','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5213232','Siniestros por Pagar por Operaciones de Coaseguro','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5213240','Ingresos Anticipados por Operaciones de Seguros','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5214000','OTROS PASIVOS','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5214100','Provisiones','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5214200','Otros Pasivos','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5214210','Impuestos por Pagar','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5214211','Cuenta por Pagar por Impuestos Corrientes','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5214212','Pasivos por Impuestos Diferidos','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5214220','Deudas Relacionados','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5214230','Deudas con Intermediarios','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5214240','Deudas con el Personal','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5214250','Ingresos Anticipados','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5214260','Otros Pasivos no Financieros','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5220000','TOTAL PATRIMONIO','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5221000','Capital Pagado','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5222000','Reservas','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5223000','Resultados Acumulados','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5223100','Resultados Acumulados Periodos Anteriores','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5223200','Resultado del Ejercicio','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5223300','(Dividendos)','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5224000','Otros Ajustes','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5311000','MARGEN DE CONTRIBUCIÓN (MC)','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5311100','Prima Retenida','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5311110','Prima Directa','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5311120','Prima Aceptada','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5311130','Prima Cedida','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5311200','Variación de Reservas Técnicas','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5311210','Variación Reserva de Riesgo en Curso','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5311220','Variación Reserva Matematica','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5311230','Variación Reserva Valor del Fondo','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5311240','Variación Reserva Catastrófica de Terremoto','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5311250','Variación Reserva Insufuciencia de Primas','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5311260','Variación Otras Reservas Técnicas','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5311300','Costo de Siniestros ','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5311310','Siniestros Directos','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5311320','Siniestros Cedidos','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5311330','Siniestros Aceptados','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5311400','Costo de Rentas','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5311410','Rentas Directas','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5311420','Rentas Cedidas','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5311430','Rentas Aceptadas','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5311500','Resultado de Intermediación','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5311510','Comisión Agentes Directos','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5311520','Comisión Corredores y Retribución Asesores Previsionales','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5311530','Comisiones de Reaseguro Aceptado','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5311540','Comisiones de Reaseguro Cedido','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5311600','Gastos por Reaseguro No Proporcional','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5311700','Gastos Médicos','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5311800','Deterioro de Seguros','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5312000','COSTOS DE ADMINISTRACIÓN (CA)','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5312100','Remuneraciones','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5312200','Otros','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5313000','RESULTADO DE INVERSIONES (RI)','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5313100','Resultado Neto Inversiones Realizadas','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5313110','Inversiones Inmobiliarias','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5313120','Inversiones Financieras','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5313200','Resultado Neto Inversiones No Realizadas','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5313210','Inversiones Inmobiliarias','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5313220','Inversiones Financieras','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5313300','Resultado Neto Inversiones Devengadas','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5313310','Inversiones Inmobiliarias','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5313320','Inversiones Financieras','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5313330','Depreciación','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5313340','Gastos de gestión','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5313400','Resultado Neto Inversiones por Seguros con Cuenta Única de Inversiones','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5313500','Deterioro de Inversiones','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5314000','RESULTADO TÉCNICO DE SEGUROS (MC + RI + CA)','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5315000','OTROS INGRESOS Y EGRESOS','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5315100','Otros Ingresos','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5315200','Otros Gastos','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5316100','Diferencia de Cambio','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5316200','Utilidad (Pérdida) por Unidades Reajustables ','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5317000','Resultado de Operaciones Continuas Antes de Impuesto Renta ','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5318000','Utilidad (Pérdida) por Operaciones Discontinuas y Disponibles para la Venta (Netas de Impuestos)','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5319000','Impuesto Renta','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5310000','TOTAL RESULTADO DEL PERIODO','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5321000','Resultado en la Evaluación Propiedades, Muebles y Equipos','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5322000','Resultado en Activos Financieros','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5323000','Resultado en Coberturas de Flujo de Caja','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5324000','Otros Resultados con Ajuste en Patrimonio','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5325000','Impuestos Diferidos','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5320000','TOTAL OTRO RESULTADO INTEGRAL','1');
Insert into REVELACIONES.REV_CODIGO_FECU (ID_FECU,DESCRIPCION,VIGENCIA) values ('5300000','TOTAL DEL RESULTADO INTEGRAL','1');

commit;