begin
for CUR_UPDATE
in(SELECT 1 FROM DUAL) loop

UPDATE REV_GRILLA SET TITULO = 'El detalle de los saldos incluidos bajo efectivo y equivalente de efectivo es el siguiente:' WHERE id_grilla =	507;
UPDATE REV_GRILLA SET TITULO = 'El detalle de los activos financieros registrados a valor razonable, es el siguiente:' WHERE id_grilla =	494;
UPDATE REV_GRILLA SET TITULO = 'El detalle de  los montos totales para las posiciones en forwards, opciones y swap, de acuerdo al objetivo del contrato, es el siguiente:' WHERE id_grilla =	518;
UPDATE REV_GRILLA SET TITULO = 'El detalle de  los montos totales para las posiciones en futuros, de acuerdo al objetivo del contrato, es el siguiente:' WHERE id_grilla =	530;
UPDATE REV_GRILLA SET TITULO = 'El detalle de las operaciones de venta corta, es el siguiente:' WHERE id_grilla =	531;
UPDATE REV_GRILLA SET TITULO = 'El detalle de los contratos de opciones, es el siguiente:' WHERE id_grilla =	561;
UPDATE REV_GRILLA SET TITULO = 'El detalle de los contratos de forwards, es el siguiente:' WHERE id_grilla =	562;
UPDATE REV_GRILLA SET TITULO = 'El detalle de los contratos de futuros, es el siguiente:' WHERE id_grilla =	569;
UPDATE REV_GRILLA SET TITULO = 'El detalle de los contratos swaps, es el siguiente:' WHERE id_grilla =	576;
UPDATE REV_GRILLA SET TITULO = 'El detalle de los contratos de cobertura de riesgo de crédito, es el siguiente:' WHERE id_grilla =	580;
UPDATE REV_GRILLA SET TITULO = 'El detalle de los activos financieros valorizados a costo amortizado, es el siguiente:' WHERE id_grilla =	593;
UPDATE REV_GRILLA SET TITULO = 'El efecto total por el deterioro de las inversiones a costo amortizado al término del periodo, se detalla a continuación:' WHERE id_grilla =	594;
UPDATE REV_GRILLA SET TITULO = 'El detalle de los compromisos efectuados sobre instrumentos financieros es el siguiente:' WHERE id_grilla =	627;
UPDATE REV_GRILLA SET TITULO = 'La estructura de los préstamos a terceros es la siguiente:' WHERE id_grilla =	527;
UPDATE REV_GRILLA SET TITULO = 'El efecto total por el deterioro de préstamos a terceros al término del periodo, se detalla a continuación:' WHERE id_grilla =	528;
UPDATE REV_GRILLA SET TITULO = 'El detalle los instrumentos financieros que respaldan inversiones con cuenta única de inversión es como sigue:' WHERE id_grilla =	488;
UPDATE REV_GRILLA SET TITULO = 'A continuación se presenta el resumen de la información financiera de las inversiones contabilizadas utilizando el método de participación:' WHERE id_grilla =	563;
UPDATE REV_GRILLA SET TITULO = 'El movimiento de las inversiones en coligadas durante el periodo, es el siguiente:' WHERE id_grilla =	532;
UPDATE REV_GRILLA SET TITULO = 'El movimiento de las inversiones en instrumentos financieros durante el periodo, es el siguiente:' WHERE id_grilla =	533;
UPDATE REV_GRILLA SET TITULO = 'La Compañía tiene las siguientes garantías otorgadas, por obligaciones de pago contraídas, al cierre del período:' WHERE id_grilla =	536;
UPDATE REV_GRILLA SET TITULO = 'La Compañía tiene las siguientes garantías recibidas  susceptibles de ser vendidas:' WHERE id_grilla =	537;
UPDATE REV_GRILLA SET TITULO = 'La tasa de reinversión del periodo es la siguiente:' WHERE id_grilla =	538;
UPDATE REV_GRILLA SET TITULO = 'El detalle de la cartera de inversiones al fin del periodo,  es el siguiente:' WHERE id_grilla =	615;
UPDATE REV_GRILLA SET TITULO = 'El detalle de la inversión en cuotas de fondo por cuenta de los asegurados, es el siguiente:' WHERE id_grilla =	609;
UPDATE REV_GRILLA SET TITULO = 'El movimiento de las inversiones en el periodo, es el siguiente	' WHERE id_grilla =585;
UPDATE REV_GRILLA SET TITULO = 'El detalle de la cuentas por cobrar, de bienes raíces entregados en arrendamiento financieros, es el siguiente:' WHERE id_grilla =	523;
UPDATE REV_GRILLA SET TITULO = 'El movimiento de estos activos en el periodo, es el siguiente:' WHERE id_grilla =	592;
UPDATE REV_GRILLA SET TITULO = 'El detalle de los activos no corrientes mantenidos para la venta, es el siguiente:' WHERE id_grilla =	553;
UPDATE REV_GRILLA SET TITULO = 'El detalle de los saldos de prima por cobrar adeudados a la Compañía es el siguiente:' WHERE id_grilla =	549;
UPDATE REV_GRILLA SET TITULO = 'La cartera de las cuentas por cobrar a asegurados tiene la siguiente estructura de antigüedad a la fecha de reporte:' WHERE id_grilla =	629;
UPDATE REV_GRILLA SET TITULO = 'El efecto total por el deterioro de cuentas por cobrar a asegurados al término del periodo, se detalla a continuación' WHERE id_grilla =	550;
UPDATE REV_GRILLA SET TITULO = 'El detalle de los deudores por primas por cobrar adeudados a la Compañía es el siguiente:' WHERE id_grilla =	554;
UPDATE REV_GRILLA SET TITULO = 'El efecto total por el deterioro de cuentas por cobrar de reaseguros al término del periodo, se detalla a continuación:	' WHERE id_grilla =555;
UPDATE REV_GRILLA SET TITULO = 'El detalle de los siniestros por cobrar a reaseguradores adeudados a la Compañía es el siguiente: ' WHERE id_grilla =	491;
UPDATE REV_GRILLA SET TITULO = 'El detalle de la participación del reaseguro en las reservas técnicas (parte activa) y  de las reservas técnicas (en el pasivo) es el siguiente:' WHERE id_grilla =	617;
UPDATE REV_GRILLA SET TITULO = 'Los activos intangibles con vida útil finita tuvieron el siguiente movimiento durante el periodo:' WHERE id_grilla =	631;
UPDATE REV_GRILLA SET TITULO = 'Los activos intangibles con vida útil indefinida, tuvieron el siguiente movimiento durante el periodo' WHERE id_grilla = 	633;
UPDATE REV_GRILLA SET TITULO = 'El monto neto de impuestos por cobrar se compone según el siguiente detalle:' WHERE id_grilla =	539;
UPDATE REV_GRILLA SET TITULO = 'El desglose de los impuestos diferidos de Activos y Pasivos con efecto en patrimonio es el siguiente:' WHERE id_grilla =	542;
UPDATE REV_GRILLA SET TITULO = 'Las diferencias temporarias para la determinación del efecto en resultados por impuestos diferidos, se detallan a continuación:' WHERE id_grilla =	541;
UPDATE REV_GRILLA SET TITULO = 'Las deudas del personal corresponden principalmente a anticipos, según el siguiente detalle: ' WHERE id_grilla =	591;
UPDATE REV_GRILLA SET TITULO = 'La Compañía presenta saldos por cobrar adeudados por los intermediarios, según el siguiente cuadro:' WHERE id_grilla =	588;
UPDATE REV_GRILLA SET TITULO = 'La Compañía mantiene lo siguientes saldos por cobrar con entidades relacionadas:' WHERE id_grilla =	638;
UPDATE REV_GRILLA SET TITULO = 'En el cuadro siguiente se detalla la retribución percibida por el personal clave de la Compañía (entendiéndose como tal los miembros de la Gerencia y los Directores) durante el periodo informado:' WHERE id_grilla =	604;
UPDATE REV_GRILLA SET TITULO = 'Durante el período se realizaron las siguientes transacciones con entidades relacionadas:' WHERE id_grilla =	543;
UPDATE REV_HTML SET TITULO = 'El detalle de gastos anticipados es el siguiente:' WHERE ID_HTML =	540;
UPDATE REV_GRILLA SET TITULO = 'A continuación se detallan los otros activos de la Compañía:' WHERE id_grilla =	605;
UPDATE REV_GRILLA SET TITULO = 'El detalle de los pasivos por este concepto se describe a continuación:' WHERE id_grilla =	544;
UPDATE REV_GRILLA SET TITULO = 'La composición del rubro es la siguiente:' WHERE id_grilla =	545;
UPDATE REV_GRILLA SET TITULO = 'Las reservas por este concepto tienen el siguiente movimiento durante el periodo:' WHERE id_grilla =	556;
UPDATE REV_GRILLA SET TITULO = 'Las reservas por este concepto tienen el siguiente movimiento durante el periodo:' WHERE id_grilla =	557;
UPDATE REV_GRILLA SET TITULO = 'Las reservas por este concepto tienen el siguiente movimiento durante el periodo:' WHERE id_grilla =	564;
UPDATE REV_GRILLA SET TITULO = 'Las reservas por este concepto tienen el siguiente movimiento durante el periodo:' WHERE id_grilla =	501;
UPDATE REV_GRILLA SET TITULO = 'Las reservas por este concepto tienen el siguiente movimiento durante el periodo:' WHERE id_grilla =	504;
UPDATE REV_GRILLA SET TITULO = 'Las reservas por este concepto tienen el siguiente movimiento durante el periodo:' WHERE id_grilla =	565;
UPDATE REV_GRILLA SET TITULO = 'Las reservas por este concepto tienen el siguiente movimiento durante el periodo:' WHERE id_grilla =	603;
UPDATE REV_GRILLA SET TITULO = 'Las reservas por este concepto tienen el siguiente movimiento durante el periodo:' WHERE id_grilla =	584;
UPDATE REV_GRILLA SET TITULO = 'Los índices para el periodo se detallan a continuación:' WHERE id_grilla =	497;
UPDATE REV_GRILLA SET TITULO = 'Las tasas para el periodo reportado, se detallan a continuación:' WHERE id_grilla =	566;
UPDATE REV_GRILLA SET TITULO = 'Las tablas aplicadas durante el periodo, son las siguientes:' WHERE id_grilla =	582;
UPDATE REV_GRILLA SET TITULO = 'Las reservas por este concepto  por grupo, se detallan a continuación:' WHERE id_grilla =	619;
UPDATE REV_GRILLA SET TITULO = 'Las reservas por este concepto tienen el siguiente movimiento durante el periodo:' WHERE id_grilla =	612;
UPDATE REV_GRILLA SET TITULO = 'La composición del rubro saldos de prima por pagar adeudados por la entidad es la siguiente:' WHERE id_grilla =	567;
UPDATE REV_GRILLA SET TITULO = 'La composición del rubro saldos por pagar por operaciones de reaseguro adeudados por la entidad, según vencimiento, es la siguiente:' WHERE id_grilla =	485;
UPDATE REV_GRILLA SET TITULO = 'El movimiento de las provisiones durante el periodo, es el siguiente:' WHERE id_grilla =	624;
UPDATE REV_GRILLA SET TITULO = 'La composición del rubro cuentas por pagar por impuestos corrientes adeudados por la entidad es la siguiente:' WHERE id_grilla =	571;
UPDATE REV_GRILLA SET TITULO = 'La composición del rubro deudas con intermediarios adeudados por la Compañía es la siguiente:' WHERE id_grilla =	572;
UPDATE REV_GRILLA SET TITULO = 'La composición del rubro deudas con el personal, adeudadas por la Compañía, es la siguiente:' WHERE id_grilla =	573;
UPDATE REV_GRILLA SET TITULO = 'La composición del rubro otros pasivos no financieros, adeudados por la Compañía, es la siguiente:' WHERE id_grilla =	607;
UPDATE REV_GRILLA SET TITULO = 'A continuación se presenta la información de los Reaseguradores y Corredores de Reaseguros con que opera la Compañía a la fecha  de los Estados Financieros' WHERE id_grilla = 493;
UPDATE REV_GRILLA SET TITULO = 'A continuación se presenta la información de los Reaseguradores y Corredores de Reaseguros con que opera la Compañía a la fecha de los Estados Financieros' WHERE ID_GRILLA = 493;
UPDATE REV_GRILLA SET TITULO = 'La variación presentada por las reservas técnicas es la siguiente:' WHERE ID_GRILLA = 496;
UPDATE REV_GRILLA SET TITULO = 'A continuación se presenta el monto total de los siniestros devengados en el periodo' WHERE ID_GRILLA = 514;
UPDATE REV_GRILLA SET TITULO = 'El detalle del gasto por concepto de deterioro, durante el periodo, se indica en el siguiente cuadro:' WHERE ID_GRILLA = 483;
UPDATE REV_GRILLA SET TITULO = 'El detalle de los gastos de administración, se indica en el siguiente cuadro:' WHERE ID_GRILLA = 515;
UPDATE REV_GRILLA SET TITULO = 'El detalle de los ingresos de inversiones inmobiliarias y financieras, en el periodo reportado, se indica en el siguiente cuadro:' WHERE ID_GRILLA = 596;
UPDATE REV_GRILLA SET TITULO = 'El detalle de los otros ingresos, durante el periodo se indica en el siguiente cuadro:' WHERE ID_GRILLA = 516;
UPDATE REV_GRILLA SET TITULO = 'El detalle de los otros gastos en el periodo, se indica en el siguiente cuadro:' WHERE ID_GRILLA = 517;
UPDATE REV_GRILLA SET TITULO = 'El detalle de las ganancias y pérdidas por concepto de diferencia de cambio  de acuerdo al activo o pasivo de origen, se indica en el siguiente cuadro' WHERE ID_GRILLA = 519;
UPDATE REV_GRILLA SET TITULO = 'El detalle del gasto por impuesto en el periodo, se indica en el siguiente cuadro' WHERE ID_GRILLA = 614;
UPDATE REV_GRILLA SET TITULO = 'La conciliación de la tasa de impuesto a la renta, calculado con arreglo a la legislación fiscal chilena y la tasa efectiva de impuestos se detallan a continuación:' WHERE ID_GRILLA = 579;
UPDATE REV_GRILLA SET TITULO = 'En el siguiente cuadro se detallan los flujos de efectivo de otros ingresos y otros egresos relacionados con las actividades de operación, de inversión y de financiamiento' WHERE ID_GRILLA = 630;
UPDATE REV_GRILLA SET TITULO = 'El detalle de los activos y pasivos expresados en su moneda de origen se presenta  en el siguiente cuadro:' WHERE ID_GRILLA = 489;
UPDATE REV_GRILLA SET TITULO = 'El detalle del movimiento de divisas por las operaciones realizadas con reaseguradores se presenta en el siguiente cuadro:' WHERE ID_GRILLA = 492;
UPDATE REV_GRILLA SET TITULO = 'El detalle, por tipo de moneda,  de las ganancias y pérdidas por diferencias de cambio reconocidas en resultados se presenta en el siguiente cuadro' WHERE ID_GRILLA = 610;
UPDATE REV_GRILLA SET TITULO = 'Información general' WHERE ID_GRILLA = 503;
UPDATE REV_GRILLA SET TITULO = '1) Seguros Accidentes, Salud y Adicionales' WHERE ID_GRILLA = 635;
UPDATE REV_GRILLA SET TITULO = '2) Seguros que no generan Reservas Matemáticas' WHERE ID_GRILLA = 636;
UPDATE REV_GRILLA SET TITULO = '3) Seguros con Reservas Matemáticas' WHERE ID_GRILLA = 637;
UPDATE REV_GRILLA SET TITULO = 'El detalle de los activos no efectivos que posee la Compañía, se presenta en el siguiente cuadro:' WHERE ID_GRILLA = 520;
end loop;
end;