ALTER TABLE REV_CATALOGO add VALIDAR_EEFF NUMBER(1) default 0;

ALTER TABLE REV_DETALLE_EEFF ADD MONTO_PESOS_MIL NUMBER(18,4);

ALTER TABLE REV_RELACION_DETALLE_EEFF ADD MONTO_PESOS_MIL NUMBER(18,4);

ALTER TABLE REV_VERSION add VALIDADO_EEFF NUMBER(1) default 0;