ALTER TABLE IFRS_DETALLE_EEFF DROP COLUMN DESCRIPCION_CUENTA;
ALTER TABLE IFRS_DETALLE_EEFF DROP COLUMN MONTO_EBS;
ALTER TABLE IFRS_DETALLE_EEFF DROP COLUMN RECLASIFICACION;
ALTER TABLE IFRS_DETALLE_EEFF DROP COLUMN MONTO_PESOS;
ALTER TABLE IFRS_DETALLE_EEFF DROP COLUMN MONTO_MILES;


ALTER TABLE IFRS_DETALLE_EEFF ADD MONTO_EBS NUMBER(18,4);
ALTER TABLE IFRS_DETALLE_EEFF ADD MONTO_RECLASIFICACION NUMBER(18,4);
ALTER TABLE IFRS_DETALLE_EEFF ADD MONTO_PESOS NUMBER(18,4);
ALTER TABLE IFRS_DETALLE_EEFF ADD MONTO_MILES NUMBER(18,4);
ALTER TABLE IFRS_DETALLE_EEFF ADD MONTO_PESOS_MIL NUMBER(18,4);
