CREATE TABLE "IFRS_XBRL_TAXONOMIA"
  (
    "ID_TAXONOMIA"   NUMBER(8,0) NOT NULL ENABLE,
    "NOMBRE"         VARCHAR2(1024 CHAR),
    "TOP_TAXONOMY"   VARCHAR2(1024 CHAR),
    "NOMBRE_ARCHIVO" VARCHAR2(1024 CHAR),
    "URI"            VARCHAR2(1024 CHAR),
    "VIGENTE"        NUMBER(1,0),
    "FECHA_TAXONOMIA" DATE,
    "USUARIO_CREACION" VARCHAR2(256 CHAR),
    "USUARIO_EDICION"  VARCHAR2(256 CHAR),
    "FECHA_CREACION" DATE,
    "FECHA_EDICION" date,
    constraint "PK_REV_XBRL_TAXONOMIA" primary key ("ID_TAXONOMIA")
  )