INSERT INTO "IFRS_TIPO_PARAMETRO" (ID_TIPO_PARAMETRO, NOMBRE) VALUES ('1', 'MAIL_CONFIG');

INSERT INTO "IFRS_PARAMETRO" (NOMBRE, VALOR, ID_TIPO_PARAMETRO) VALUES ('TIPO_SMTP', 'GOOGLE', '1');
INSERT INTO "IFRS_PARAMETRO" (NOMBRE, VALOR, ID_TIPO_PARAMETRO) VALUES ('SMTP_HOST', 'smtp.gmail.com', '1');
INSERT INTO "IFRS_PARAMETRO" (NOMBRE, VALOR, ID_TIPO_PARAMETRO) VALUES ('SMTP_USER', 'contacto@mdrtech.cl', '1');
INSERT INTO "IFRS_PARAMETRO" (NOMBRE, VALOR, ID_TIPO_PARAMETRO) VALUES ('SMTP_PASSWORD', 'admin.2010', '1');
INSERT INTO "IFRS_PARAMETRO" (NOMBRE, VALOR, ID_TIPO_PARAMETRO) VALUES ('SMTP_PORT', '25', '1');
INSERT INTO "IFRS_PARAMETRO" (NOMBRE, VALOR, ID_TIPO_PARAMETRO) VALUES ('MAIL_FROM', 'administrador@exfida.com', '1')

commit;



