alter table REV_CATALOGO add VALIDAR_EEFF NUMBER(1);

ALTER TABLE REV_DETALLE_EEFF ADD MONTO_PESOS_MIL NUMBER(18,4);

ALTER TABLE REV_RELACION_DETALLE_EEFF ADD MONTO_PESOS_MIL NUMBER(18,4);

ALTER TABLE REV_USUARIO_GRUPO ADD EMAIL VARCHAR2(128);