/*CREA TLABLA PARA AUDITORIA DE GENERACION DE REPORTE WORD*/
create table REV_HISTORIAL_REPORTE 
(
   ID_HISTORIAL_REPORTE NUMBER(10,0)         not null,
   COMENTARIO           VARCHAR2(1024 CHAR),
   USUARIO_OID          VARCHAR2(256 CHAR),
   IP_USUARIO           VARCHAR2(256 CHAR),
   CHECK_SUM_EXPORTACION VARCHAR2(512 CHAR),
   FECHA_EXPORTACION    DATE,
   DOCUMENTO            BLOB,
   NOMBRE_ARCHIVO       VARCHAR2(512 CHAR),
   ID_PERIODO           NUMBER(4,0),
   constraint PK_REV_HISTORIAL_REPORTE primary key (ID_HISTORIAL_REPORTE)
);

comment on table REV_HISTORIAL_REPORTE is
'TABLA QUE ALMACENA UN HISTORIAL CON LA GENERACION DEL REPORTE FINAL FECU EN FORMATO MS WORD,
ALMACENANDO EL CHECKSUM MD5 DEL ARCHIVO GENERADO PARA ASI COMPARAR SI EXISTIERON MIDIFICACIONES EN EL DOCUMENTO.';

alter table REV_HISTORIAL_REPORTE
   add constraint FK_REV_HIST_REFERENCE_REV_PERI foreign key (ID_PERIODO)
      references REV_PERIODO (ID_PERIODO);

/*CREA SECUENCIA PARA AUDITORIA DE GENERACION DE REPORTE WORD*/	  
create sequence SEQ_HISTORIAL_REPORTE
MINVALUE 0 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 0 NOCACHE  NOORDER  NOCYCLE;	  

/*ACTUALIZA COMPOS DE ALMACENAMIENTO DE FORMULAS*/
alter table REV_CELDA rename column GRUPO to CHILD_VERTICAL;

alter table REV_CELDA rename column GRUPO_RESULTADO to PARENT_VERTICAL;

alter table REV_CELDA add CHILD_HORIZONTAL NUMBER(4);

alter table REV_CELDA add PARENT_HORIZONTAL NUMBER(4);

alter table REV_CELDA add FORMULA VARCHAR2(256);

/*AGREGA CAMPO DE BLOQUEO AL SISTEMA POR GRUPOS DE USUARIO*/
alter table REV_GRUPO add ACCESO_BLOQUEADO NUMBER(1);
	  
	  
/*COPIADO DE FORMULA DE TABLAS ANTIGUAS A CAMPOS NUEVOS*/
BEGIN

DECLARE

V_FORMULA VARCHAR2(256);

BEGIN

FOR CF IN(SELECT ID_CAMPO_FORMULA, ID_COLUMNA, ID_FILA, ID_GRILLA  FROM REV_CAMPO_FORMULA  ORDER BY ID_COLUMNA, ID_FILA) LOOP

  V_FORMULA := '';

  FOR FG IN(SELECT ID_CAMPO_FORMULA, ID_COLUMNA, ID_FILA, ID_GRILLA FROM REV_FORMULA_GRILLA WHERE ID_GRILLA = CF.ID_GRILLA AND ID_CAMPO_FORMULA = CF.ID_CAMPO_FORMULA ORDER BY ID_COLUMNA, ID_FILA) LOOP
  
    V_FORMULA := V_FORMULA || '+[' || FG.ID_COLUMNA || ',' || FG.ID_FILA || '];';
  
  END LOOP;
  
    UPDATE REV_CELDA CE  SET FORMULA = V_FORMULA WHERE CE.ID_COLUMNA =  CF.ID_COLUMNA AND CE.ID_FILA = CF.ID_FILA AND CE.ID_GRILLA = CF.ID_GRILLA;
  
    --DBMS_OUTPUT.PUT_LINE(V_FORMULA);
  
END LOOP;

END;

END;

COMMIT;

/*actualiza formula = null, cuando el tipo de celda no es total ni subtotal*/
update rev_celda set formula = null where id_tipo_celda not in(4,5) and formula is not null;
commit;

update rev_celda set formula = null, parent_vertical = null, parent_horizontal = null
where id_tipo_celda not in(4,5) and  (parent_vertical is not null or parent_horizontal is not null);

delete from rev_estructura where id_estructura = 645;

update rev_estructura set orden = 1 where id_estructura = 646;

/*BORRADO DE TABLAS CON FORMULAS ANTIGUAS*/
DROP TABLE REV_FORMULA_GRILLA;

DROP TABLE REV_CAMPO_FORMULA;

/*ACTUALIZA URL DE PAGINA NUEVA DE FORMULAS*/
update rev_menu set url_menu = '/pages/mantenedores/mantenedor-formula.jsf', NOMBRE = 'Mantenedor Fórmulas' where id_menu = 17;
commit;

/*MENU DE AUDITORIA DE REPORTE*/
INSERT
INTO REV_MENU(ID_MENU, NOMBRE, ESTADO, GRUPO, URL_MENU, ES_PADRE)
VALUES(22, 'Historial de Generación de Reportes MS Word', 1, 7, '/pages/reporte/historial-reporte.jsf', 0);

/*MENU DE BLOQUEO DE INGRESO DE INFORMACION*/
INSERT
INTO REV_MENU(ID_MENU, NOMBRE, ESTADO, GRUPO, URL_MENU, ES_PADRE)
VALUES(23, 'Perfilamiento - Bloqueo del Sistema', 1, 7, '/pages/perfilamiento/bloqueo-grupo.jsf', 0);

