INSERT INTO REV_AREA_NEGOCIO (ID_AREA_NEGOCIO, NOMBRE) VALUES ('ROP', 'RIESGO OPERACIONAL')
INSERT INTO REV_GRUPO (ID_GRUPO_ACCESO, ID_AREA_NEGOCIO, ID_GRUPO_OID, NOMBRE) VALUES ('GRP_SUP_ROP', 'ROP', 'IFRS_SUPERVISOR', 'Supervisor Riesgo Operacional')
INSERT INTO REV_GRUPO (ID_GRUPO_ACCESO, ID_AREA_NEGOCIO, ID_GRUPO_OID, NOMBRE) VALUES ('GRP_ENC_ROP ', 'ROP', 'IFRS_ENCARGADO', 'Encargado Riesgo Operacional')



