package cl.bicevida.revelaciones.ejb.reporte.util;


import cl.bicevida.revelaciones.ejb.cross.Util;
import cl.bicevida.revelaciones.ejb.entity.DatoCaratulaFecu;

import java.util.Map;

import javax.xml.bind.JAXBException;

import org.docx4j.XmlUtils;
import org.docx4j.jaxb.Context;
import org.docx4j.openpackaging.contenttype.ContentType;
import org.docx4j.openpackaging.exceptions.InvalidFormatException;
import org.docx4j.openpackaging.packages.WordprocessingMLPackage;
import org.docx4j.openpackaging.parts.PartName;
import org.docx4j.openpackaging.parts.WordprocessingML.AlternativeFormatInputPart;
import org.docx4j.relationships.Relationship;
import org.docx4j.wml.CTAltChunk;
import org.docx4j.wml.R;


public class CaratulaFecuHelper {

    public CaratulaFecuHelper() {
        super();
    }

    public static String getPortadaFecuHtml(Map<String, DatoCaratulaFecu> datoCaratulaFecuMap) {
        StringBuffer html = new StringBuffer();
        html.append("<div style=\"font:Arial, Helvetica, sans-serif;\">");
        html.append("<table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\n");
        html.append("  <tr>\n");
        html.append("    <td colspan=\"3\" align=\"right\"><b style='mso-bidi-font-weight:\n");
        html.append("normal'><span style=\"font-size:14.0pt;mso-bidi-font-size:8.0pt;line-height:\n");
        html.append("115%;font-family:Arial\">FECU (Ficha Estadística Codificada\n");
        html.append("  Uniforme) </span></b></td>\n");
        html.append("  </tr>\n");
        html.append("  <tr>\n");
        html.append("    <td colspan=\"3\" align=\"right\"><p><b style='mso-bidi-font-weight:\n");
        html.append("normal'><span style=\"font-size:10.0pt;mso-bidi-font-size:8.0pt;line-height:\n");
        html.append("115%;font-family:Arial\">COMPAÑIAS DEL SEGUNDO GRUPO</span></b></p></td>\n");
        html.append("  </tr>\n");
        html.append("  <tr>\n");
        html.append("    <td>&nbsp;</td>\n");
        html.append("    <td>&nbsp;</td>\n");
        html.append("    <td>&nbsp;</td>\n");
        html.append("  </tr>\n");
        html.append("</table>\n");
        html.append("<p>&nbsp;</p>\n");
        html.append("<div style=\"font-size:10.0pt;mso-bidi-font-size:8.0pt;line-height:115%;font-family:Arial\">");
        html.append("<table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"font-size:10.0pt;mso-bidi-font-size:8.0pt;line-height:\n");
        html.append("115%;font-family:Arial\">\n");
        html.append("  <tr>\n");
        html.append("    <td width=\"199\" valign=\"top\"><p>&nbsp;</p></td>\n");
        html.append("    <td width=\"399\" colspan=\"2\" valign=\"top\"><p align=\"center\">PERÍODO INFORMADO</p></td>\n");
        html.append("  </tr>\n");
        html.append("  <tr>\n");
        html.append("    <td width=\"199\" valign=\"top\"><p>&nbsp;</p></td>\n");
        html.append("    <td width=\"200\" valign=\"top\"><p align=\"center\">&nbsp;</p></td>\n");
        html.append("    <td width=\"200\" valign=\"top\"><p align=\"center\">&nbsp;</p></td>\n");
        html.append("  </tr>\n");
        html.append("  <tr>\n");
        html.append("    <td width=\"199\" valign=\"top\"><p>&nbsp;</p></td>\n");
        html.append("    <td width=\"200\" valign=\"top\"><p style=\"font-size:10.0pt;mso-bidi-font-size:8.0pt;line-height:\n");
        html.append("115%;font-family:Arial\" align=\"center\"><strong>").append(Util.getString(datoCaratulaFecuMap.get("FECHA_INICIO").getNombreDatoCaratulaFecu().getGlosaDato(), "")).append("</strong></p></td>\n");
        html.append("    <td width=\"200\" valign=\"top\"><p style=\"font-size:10.0pt;mso-bidi-font-size:8.0pt;line-height:\n");
        html.append("115%;font-family:Arial\" align=\"center\"><strong>").append(Util.getString(datoCaratulaFecuMap.get("FECHA_TERMINO").getNombreDatoCaratulaFecu().getGlosaDato(), "")).append("</strong></p></td>\n");
        html.append("  </tr>\n");
        html.append("  <tr>\n");
        html.append("    <td width=\"199\" valign=\"top\"><p>&nbsp;</p></td>\n");
        html.append("    <td width=\"200\" style=\"border:1px solid;\"><p style=\"font-size:10.0pt;mso-bidi-font-size:8.0pt;line-height:\n");
        html.append("115%;font-family:Arial\" align=\"center\">").append(Util.getString(datoCaratulaFecuMap.get("FECHA_INICIO").getValor(), "")).append("</p></td>\n");
        html.append("    <td width=\"200\" style=\"border:1px solid;\"><p style=\"font-size:10.0pt;mso-bidi-font-size:8.0pt;line-height:\n");
        html.append("115%;font-family:Arial\" align=\"center\">").append(Util.getString(datoCaratulaFecuMap.get("FECHA_TERMINO").getValor(), "")).append("</p></td>\n");
        html.append("  </tr>\n");
        html.append("</table>\n");
        html.append("<p>&nbsp;</p>\n");
        html.append("<table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"font-size:10.0pt;mso-bidi-font-size:8.0pt;line-height:\n");
        html.append("115%;font-family:Arial\">\n");
        html.append("  <tr>\n");
        html.append("    <td width=\"149\"><p style=\"font-size:10.0pt;mso-bidi-font-size:8.0pt;line-height:\n");
        html.append("115%;font-family:Arial\"><strong>").append(Util.getString(datoCaratulaFecuMap.get("NOMBRE_FANTASIA").getNombreDatoCaratulaFecu().getGlosaDato(), "")).append("</strong></p></td>\n");
        html.append("    <td width=\"450\" style=\"border:1px solid;\"><p style=\"font-size:10.0pt;mso-bidi-font-size:8.0pt;line-height:\n");
        html.append("115%;font-family:Arial\">").append(Util.getString(datoCaratulaFecuMap.get("NOMBRE_FANTASIA").getValor(), "")).append("</p></td>\n");
        html.append("  </tr>\n");
        html.append("</table>\n");
        html.append("<p>&nbsp;</p>\n");
        html.append("<p style=\"font-size:10.0pt;mso-bidi-font-size:8.0pt;line-height:\n");
        html.append("115%;font-family:Arial\"><strong>1.- IDENTIFICACION</strong></p>\n");
        html.append("<table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"font-size:10.0pt;mso-bidi-font-size:8.0pt;line-height:\n");
        html.append("115%;font-family:Arial\">\n");
        html.append("  <tr>\n");
        html.append("    <td width=\"100%\" valign=\"top\">\n");
        html.append("    <table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\n");
        html.append("      <tr>\n");
        html.append("        <td colspan=\"2\"><p>&nbsp;</p></td>\n");
        html.append("        <td><p>&nbsp;</p></td>\n");
        html.append("        <td><p><strong>&nbsp;</strong></p></td>\n");
        html.append("        <td><p>&nbsp;</p></td>\n");
        html.append("      </tr>\n");
        html.append("      <tr>\n");
        html.append("        <td colspan=\"2\"><p>&nbsp;</p></td>\n");
        html.append("        <td><p>&nbsp;</p></td>\n");
        html.append("        <td><p style=\"font-size:10.0pt;mso-bidi-font-size:8.0pt;line-height:\n");
        html.append("115%;font-family:Arial\"><strong>").append(Util.getString(datoCaratulaFecuMap.get("RUT").getNombreDatoCaratulaFecu().getGlosaDato(), "")).append("</strong></p></td>\n");
        html.append("        <td style=\"border:1px solid;\"><p style=\"font-size:10.0pt;mso-bidi-font-size:8.0pt;line-height:\n");
        html.append("115%;font-family:Arial\">").append(Util.getString(datoCaratulaFecuMap.get("RUT").getValor(), "")).append("</p></td>\n");
        html.append("      </tr>\n");
        html.append("      <tr>\n");
        html.append("        <td colspan=\"3\"><p style=\"font-size:10.0pt;mso-bidi-font-size:8.0pt;line-height:\n");
        html.append("115%;font-family:Arial\"><strong>").append(Util.getString(datoCaratulaFecuMap.get("RAZON_SOCIAL").getNombreDatoCaratulaFecu().getGlosaDato(), "")).append("</strong></p></td>\n");
        html.append("        <td><p>&nbsp;</p></td>\n");
        html.append("        <td><p>&nbsp;</p></td>\n");
        html.append("      </tr>\n");
        html.append("      <tr>\n");
        html.append("        <td colspan=\"3\" style=\"border:1px solid;\"><p style=\"font-size:10.0pt;mso-bidi-font-size:8.0pt;line-height:\n");
        html.append("115%;font-family:Arial\">").append(Util.getString(datoCaratulaFecuMap.get("RAZON_SOCIAL").getValor(), "")).append("</p></td>\n");
        html.append("        <td><p style=\"font-size:10.0pt;mso-bidi-font-size:8.0pt;line-height:\n");
        html.append("115%;font-family:Arial\"><strong>").append(Util.getString(datoCaratulaFecuMap.get("TELEFONO").getNombreDatoCaratulaFecu().getGlosaDato(), "")).append("</strong></p></td>\n");
        html.append("        <td style=\"border:1px solid;\"><p style=\"font-size:10.0pt;mso-bidi-font-size:8.0pt;line-height:\n");
        html.append("115%;font-family:Arial\">").append(Util.getString(datoCaratulaFecuMap.get("TELEFONO").getValor(), "")).append("</p></td>\n");
        html.append("      </tr>\n");
        html.append("      <tr>\n");
        html.append("        <td colspan=\"3\"><p style=\"font-size:10.0pt;mso-bidi-font-size:8.0pt;line-height:\n");
        html.append("115%;font-family:Arial\"><strong>").append(Util.getString(datoCaratulaFecuMap.get("NOMBRE_FANTASIA").getNombreDatoCaratulaFecu().getGlosaDato(), "")).append("</strong></p></td>\n");
        html.append("        <td><p style=\"font-size:10.0pt;mso-bidi-font-size:8.0pt;line-height:\n");
        html.append("115%;font-family:Arial\"><strong>").append(Util.getString(datoCaratulaFecuMap.get("CASILLA").getNombreDatoCaratulaFecu().getGlosaDato(), "")).append("</strong><strong> </strong></p></td>\n");
        html.append("        <td style=\"border:1px solid;\"><p style=\"font-size:10.0pt;mso-bidi-font-size:8.0pt;line-height:\n");
        html.append("115%;font-family:Arial\">").append(Util.getString(datoCaratulaFecuMap.get("CASILLA").getValor(), "")).append("</p></td>\n");
        html.append("      </tr>\n");
        html.append("      <tr>\n");
        html.append("        <td colspan=\"3\" style=\"border:1px solid;\"><p style=\"font-size:10.0pt;mso-bidi-font-size:8.0pt;line-height:\n");
        html.append("115%;font-family:Arial\">").append(Util.getString(datoCaratulaFecuMap.get("NOMBRE_FANTASIA").getValor(), "")).append("</p></td>\n");
        html.append("        <td><p style=\"font-size:10.0pt;mso-bidi-font-size:8.0pt;line-height:\n");
        html.append("115%;font-family:Arial\"><strong>").append(Util.getString(datoCaratulaFecuMap.get("FAX").getNombreDatoCaratulaFecu().getGlosaDato(), "")).append("</strong></p></td>\n");
        html.append("        <td style=\"border:1px solid;\"><p style=\"font-size:10.0pt;mso-bidi-font-size:8.0pt;line-height:\n");
        html.append("115%;font-family:Arial\">").append(Util.getString(datoCaratulaFecuMap.get("FAX").getValor(), "")).append("</p></td>\n");
        html.append("      </tr>\n");
        html.append("      <tr>\n");
        html.append("        <td colspan=\"3\"><p style=\"font-size:10.0pt;mso-bidi-font-size:8.0pt;line-height:\n");
        html.append("115%;font-family:Arial\"><strong>").append(Util.getString(datoCaratulaFecuMap.get("DOMICILIO_LEGAL").getNombreDatoCaratulaFecu().getGlosaDato(), "")).append("</strong></p></td>\n");
        html.append("        <td><p style=\"font-size:10.0pt;mso-bidi-font-size:8.0pt;line-height:\n");
        html.append("115%;font-family:Arial\"><strong>").append(Util.getString(datoCaratulaFecuMap.get("EMAIL").getNombreDatoCaratulaFecu().getGlosaDato(), "")).append("</strong></p></td>\n");
        html.append("        <td style=\"border:1px solid;\"><p style=\"font-size:10.0pt;mso-bidi-font-size:8.0pt;line-height:\n");
        html.append("115%;font-family:Arial\">").append(Util.getString(datoCaratulaFecuMap.get("EMAIL").getValor(), "")).append("</p></td>\n");
        html.append("      </tr>\n");
        html.append("      <tr>\n");
        html.append("        <td colspan=\"3\" style=\"border:1px solid;\"><p style=\"font-size:10.0pt;mso-bidi-font-size:8.0pt;line-height:\n");
        html.append("115%;font-family:Arial\">").append(Util.getString(datoCaratulaFecuMap.get("DOMICILIO_LEGAL").getValor(), "")).append("</p></td>\n");
        html.append("        <td><p style=\"font-size:10.0pt;mso-bidi-font-size:8.0pt;line-height:\n");
        html.append("115%;font-family:Arial\"><strong>").append(Util.getString(datoCaratulaFecuMap.get("CODIGO").getNombreDatoCaratulaFecu().getGlosaDato(), "")).append("</strong></p></td>\n");
        html.append("        <td style=\"border:1px solid;\"><p style=\"font-size:10.0pt;mso-bidi-font-size:8.0pt;line-height:\n");
        html.append("115%;font-family:Arial\">").append(Util.getString(datoCaratulaFecuMap.get("CODIGO").getValor(), "")).append("</p></td>\n");
        html.append("      </tr>\n");
        html.append("      <tr>\n");
        html.append("        <td><p><strong>&nbsp;</strong></p></td>\n");
        html.append("        <td colspan=\"2\"><p>&nbsp;</p></td>\n");
        html.append("        <td><p>&nbsp;</p></td>\n");
        html.append("        <td><p>&nbsp;</p></td>\n");
        html.append("      </tr>\n");
        html.append("      <tr>\n");
        html.append("        <td><p style=\"font-size:10.0pt;mso-bidi-font-size:8.0pt;line-height:\n");
        html.append("115%;font-family:Arial\"><strong>").append(Util.getString(datoCaratulaFecuMap.get("CIUDAD").getNombreDatoCaratulaFecu().getGlosaDato(), "")).append("</strong></p></td>\n");
        html.append("        <td colspan=\"2\" style=\"border:1px solid;\"><p style=\"font-size:10.0pt;mso-bidi-font-size:8.0pt;line-height:\n");
        html.append("115%;font-family:Arial\">").append(Util.getString(datoCaratulaFecuMap.get("CIUDAD").getValor(), "")).append("</p></td>\n");
        html.append("        <td><p>&nbsp;</p></td>\n");
        html.append("        <td><p>&nbsp;</p></td>\n");
        html.append("      </tr>\n");
        html.append("      <tr>\n");
        html.append("        <td><p style=\"font-size:10.0pt;mso-bidi-font-size:8.0pt;line-height:\n");
        html.append("115%;font-family:Arial\"><strong>").append(Util.getString(datoCaratulaFecuMap.get("REGION").getNombreDatoCaratulaFecu().getGlosaDato(), "")).append("</strong></p></td>\n");
        html.append("        <td colspan=\"2\" style=\"border:1px solid;\"><p style=\"font-size:10.0pt;mso-bidi-font-size:8.0pt;line-height:\n");
        html.append("115%;font-family:Arial\">").append(Util.getString(datoCaratulaFecuMap.get("REGION").getValor(), "")).append("</p></td>\n");
        html.append("        <td><p>&nbsp;</p></td>\n");
        html.append("        <td><p>&nbsp;</p></td>\n");
        html.append("      </tr>\n");
        html.append("      <tr>\n");
        html.append("        <td><p><strong>&nbsp;</strong></p></td>\n");
        html.append("        <td colspan=\"2\"><p>&nbsp;</p></td>\n");
        html.append("        <td><p>&nbsp;</p></td>\n");
        html.append("        <td><p>&nbsp;</p></td>\n");
        html.append("      </tr>\n");
        html.append("    </table></td>\n");
        html.append("  </tr>\n");
        html.append("</table>\n");
        html.append("<br />\n");
        html.append("<p style=\"font-size:10.0pt;mso-bidi-font-size:8.0pt;line-height:\n");
        html.append("115%;font-family:Arial\"><strong>2.- ADMINISTRACION</strong></p>\n");
        html.append("<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" style=\"font-size:10.0pt;mso-bidi-font-size:8.0pt;line-height:\n");
        html.append("115%;font-family:Arial\">\n");
        html.append("  <tr>\n");
        html.append("    <td width=\"100%\" valign=\"top\">\n");
        html.append("    <table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\n");
        html.append("      <tr>\n");
        html.append("        <td width=\"71%\"><p><strong>&nbsp;</strong></p></td>\n");
        html.append("        <td width=\"3%\"><p><strong>&nbsp;</strong></p></td>\n");
        html.append("        <td width=\"26%\"><p><strong>&nbsp;</strong></p></td>\n");
        html.append("      </tr>\n");
        html.append("      <tr>\n");
        html.append("        <td><p style=\"font-size:10.0pt;mso-bidi-font-size:8.0pt;line-height:\n");
        html.append("115%;font-family:Arial\"><strong>").append(Util.getString(datoCaratulaFecuMap.get("REPRESENTANTE_LEGAL").getNombreDatoCaratulaFecu().getGlosaDato(), "")).append("</strong></p></td>\n");
        html.append("        <td><p><strong>&nbsp;</strong></p></td>\n");
        html.append("        <td><p style=\"font-size:10.0pt;mso-bidi-font-size:8.0pt;line-height:\n");
        html.append("115%;font-family:Arial\"><strong>").append(Util.getString(datoCaratulaFecuMap.get("RUT_REPRESENTANTE_LEGAL").getNombreDatoCaratulaFecu().getGlosaDato(), "")).append("</strong></p></td>\n");
        html.append("      </tr>\n");
        html.append("      <tr>\n");
        html.append("        <td style=\"border:1px solid;\"><p style=\"font-size:10.0pt;mso-bidi-font-size:8.0pt;line-height:\n");
        html.append("115%;font-family:Arial\">").append(Util.getString(datoCaratulaFecuMap.get("REPRESENTANTE_LEGAL").getValor(), "")).append("</p></td>\n");
        html.append("        <td><p><strong>&nbsp;</strong></p></td>\n");
        html.append("        <td style=\"border:1px solid;\"><p style=\"font-size:10.0pt;mso-bidi-font-size:8.0pt;line-height:\n");
        html.append("115%;font-family:Arial\">").append(Util.getString(datoCaratulaFecuMap.get("RUT_REPRESENTANTE_LEGAL").getValor(), "")).append("</p></td>\n");
        html.append("      </tr>\n");
        html.append("      <tr>\n");
        html.append("        <td><p style=\"font-size:10.0pt;mso-bidi-font-size:8.0pt;line-height:\n");
        html.append("115%;font-family:Arial\"><strong>").append(Util.getString(datoCaratulaFecuMap.get("GERENTE_GENERAL").getNombreDatoCaratulaFecu().getGlosaDato(), "")).append("</strong></p></td>\n");
        html.append("        <td><p><strong>&nbsp;</strong></p></td>\n");
        html.append("        <td><p>&nbsp;</p></td>\n");
        html.append("      </tr>\n");
        html.append("      <tr>\n");
        html.append("        <td style=\"border:1px solid;\"><p style=\"font-size:10.0pt;mso-bidi-font-size:8.0pt;line-height:\n");
        html.append("115%;font-family:Arial\">").append(Util.getString(datoCaratulaFecuMap.get("GERENTE_GENERAL").getValor(), "")).append("</p></td>\n");
        html.append("        <td><p><strong>&nbsp;</strong></p></td>\n");
        html.append("        <td style=\"border:1px solid;\"><p style=\"font-size:10.0pt;mso-bidi-font-size:8.0pt;line-height:\n");
        html.append("115%;font-family:Arial\">").append(Util.getString(datoCaratulaFecuMap.get("RUT_GERENTE_GENERAL").getValor(), "")).append("</p></td>\n");
        html.append("      </tr>\n");
        html.append("      <tr>\n");
        html.append("        <td><p style=\"font-size:10.0pt;mso-bidi-font-size:8.0pt;line-height:\n");
        html.append("115%;font-family:Arial\"><strong>").append(Util.getString(datoCaratulaFecuMap.get("GERENTE_FINANZAS").getNombreDatoCaratulaFecu().getGlosaDato(), "")).append("</strong></p></td>\n");
        html.append("        <td><p><strong>&nbsp;</strong></p></td>\n");
        html.append("        <td><p>&nbsp;</p></td>\n");
        html.append("      </tr>\n");
        html.append("      <tr>\n");
        html.append("        <td style=\"border:1px solid;\"><p style=\"font-size:10.0pt;mso-bidi-font-size:8.0pt;line-height:\n");
        html.append("115%;font-family:Arial\">").append(Util.getString(datoCaratulaFecuMap.get("GERENTE_FINANZAS").getValor(), "")).append("</p></td>\n");
        html.append("        <td><p><strong>&nbsp;</strong></p></td>\n");
        html.append("        <td style=\"border:1px solid;\"><p style=\"font-size:10.0pt;mso-bidi-font-size:8.0pt;line-height:\n");
        html.append("115%;font-family:Arial\">").append(Util.getString(datoCaratulaFecuMap.get("RUT_GERENTE_FINANZAS").getValor(), "")).append("</p></td>\n");
        html.append("      </tr>\n");
        html.append("      <tr>\n");
        html.append("        <td><p style=\"font-size:10.0pt;mso-bidi-font-size:8.0pt;line-height:\n");
        html.append("115%;font-family:Arial\"><strong>").append(Util.getString(datoCaratulaFecuMap.get("PRESIDENTE_DIRECTORIO").getNombreDatoCaratulaFecu().getGlosaDato(), "")).append("</strong></p></td>\n");
        html.append("        <td><p><strong>&nbsp;</strong></p></td>\n");
        html.append("        <td><p>&nbsp;</p></td>\n");
        html.append("      </tr>\n");
        html.append("      <tr>\n");
        html.append("        <td style=\"border:1px solid;\"><p style=\"font-size:10.0pt;mso-bidi-font-size:8.0pt;line-height:\n");
        html.append("115%;font-family:Arial\">").append(Util.getString(datoCaratulaFecuMap.get("PRESIDENTE_DIRECTORIO").getValor(), "")).append("</p></td>\n");
        html.append("        <td><p><strong>&nbsp;</strong></p></td>\n");
        html.append("        <td style=\"border:1px solid;\"><p style=\"font-size:10.0pt;mso-bidi-font-size:8.0pt;line-height:\n");
        html.append("115%;font-family:Arial\">").append(Util.getString(datoCaratulaFecuMap.get("RUT_PRESIDENTE_DIRECTORIO").getValor(), "")).append("</p></td>\n");
        html.append("      </tr>\n");
        html.append("    </table>\n");
        html.append("      <table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\n");
        html.append("        <tr>\n");
        html.append("          <td width=\"71%\"><p style=\"font-size:10.0pt;mso-bidi-font-size:8.0pt;line-height:\n");
        html.append("115%;font-family:Arial\"><strong>").append(Util.getString(datoCaratulaFecuMap.get("DIRECTOR_1").getNombreDatoCaratulaFecu().getGlosaDato(), "")).append("</strong></p></td>\n");
        html.append("          <td width=\"3%\"><p><strong>&nbsp;</strong></p></td>\n");
        html.append("          <td width=\"26%\"><p><strong>&nbsp;</strong></p></td>\n");
        html.append("        </tr>\n");
        html.append("        <tr>\n");
        html.append("          <td style=\"border:1px solid;\"><p style=\"font-size:10.0pt;mso-bidi-font-size:8.0pt;line-height:\n");
        html.append("115%;font-family:Arial\">").append(Util.getString(datoCaratulaFecuMap.get("DIRECTOR_1").getValor(), "")).append("</p></td>\n");
        html.append("          <td><p><strong>&nbsp;</strong></p></td>\n");
        html.append("          <td style=\"border:1px solid;\"><p style=\"font-size:10.0pt;mso-bidi-font-size:8.0pt;line-height:\n");
        html.append("115%;font-family:Arial\">").append(Util.getString(datoCaratulaFecuMap.get("RUT_DIRECTOR_1").getValor(), "")).append("</p></td>\n");
        html.append("        </tr>\n");
        html.append("        <tr>\n");
        html.append("          <td style=\"border:1px solid;\"><p style=\"font-size:10.0pt;mso-bidi-font-size:8.0pt;line-height:\n");
        html.append("115%;font-family:Arial\">").append(Util.getString(datoCaratulaFecuMap.get("DIRECTOR_2").getValor(), "")).append("<strong></strong></p></td>\n");
        html.append("          <td><p><strong>&nbsp;</strong></p></td>\n");
        html.append("          <td style=\"border:1px solid;\"><p style=\"font-size:10.0pt;mso-bidi-font-size:8.0pt;line-height:\n");
        html.append("115%;font-family:Arial\">").append(Util.getString(datoCaratulaFecuMap.get("RUT_DIRECTOR_2").getValor(), "")).append("<strong></strong></p></td>\n");
        html.append("        </tr>\n");
        html.append("        <tr>\n");
        html.append("          <td style=\"border:1px solid;\"><p style=\"font-size:10.0pt;mso-bidi-font-size:8.0pt;line-height:\n");
        html.append("115%;font-family:Arial\">").append(Util.getString(datoCaratulaFecuMap.get("DIRECTOR_3").getValor(), "")).append("<strong></strong></p></td>\n");
        html.append("          <td><p><strong>&nbsp;</strong></p></td>\n");
        html.append("          <td style=\"border:1px solid;\"><p style=\"font-size:10.0pt;mso-bidi-font-size:8.0pt;line-height:\n");
        html.append("115%;font-family:Arial\">").append(Util.getString(datoCaratulaFecuMap.get("RUT_DIRECTOR_3").getValor(), "")).append("<strong></strong></p></td>\n");
        html.append("        </tr>\n");
        html.append("        <tr>\n");
        html.append("          <td style=\"border:1px solid;\"><p style=\"font-size:10.0pt;mso-bidi-font-size:8.0pt;line-height:\n");
        html.append("115%;font-family:Arial\">").append(Util.getString(datoCaratulaFecuMap.get("DIRECTOR_4").getValor(), "")).append("<strong></strong></p></td>\n");
        html.append("          <td><p><strong>&nbsp;</strong></p></td>\n");
        html.append("          <td style=\"border:1px solid;\"><p style=\"font-size:10.0pt;mso-bidi-font-size:8.0pt;line-height:\n");
        html.append("115%;font-family:Arial\">").append(Util.getString(datoCaratulaFecuMap.get("RUT_DIRECTOR_4").getValor(), "")).append("<strong></strong></p></td>\n");
        html.append("        </tr>\n");
        html.append("        <tr>\n");
        html.append("          <td style=\"border:1px solid;\"><p style=\"font-size:10.0pt;mso-bidi-font-size:8.0pt;line-height:\n");
        html.append("115%;font-family:Arial\">").append(Util.getString(datoCaratulaFecuMap.get("DIRECTOR_5").getValor(), "")).append("<strong></strong></p></td>\n");
        html.append("          <td><p><strong>&nbsp;</strong></p></td>\n");
        html.append("          <td style=\"border:1px solid;\"><p style=\"font-size:10.0pt;mso-bidi-font-size:8.0pt;line-height:\n");
        html.append("115%;font-family:Arial\">").append(Util.getString(datoCaratulaFecuMap.get("RUT_DIRECTOR_5").getValor(), "")).append("<strong></strong></p></td>\n");
        html.append("        </tr>\n");
        html.append("        <tr>\n");
        html.append("          <td style=\"border:1px solid;\"><p style=\"font-size:10.0pt;mso-bidi-font-size:8.0pt;line-height:\n");
        html.append("115%;font-family:Arial\">").append(Util.getString(datoCaratulaFecuMap.get("DIRECTOR_6").getValor(), "")).append("<strong></strong></p></td>\n");
        html.append("          <td><p><strong>&nbsp;</strong></p></td>\n");
        html.append("          <td style=\"border:1px solid;\"><p style=\"font-size:10.0pt;mso-bidi-font-size:8.0pt;line-height:\n");
        html.append("115%;font-family:Arial\">").append(Util.getString(datoCaratulaFecuMap.get("RUT_DIRECTOR_6").getValor(), "")).append("<strong></strong></p></td>\n");
        html.append("        </tr>\n");
        html.append("        <tr>\n");
        html.append("          <td style=\"border:1px solid;\"><p style=\"font-size:10.0pt;mso-bidi-font-size:8.0pt;line-height:\n");
        html.append("115%;font-family:Arial\">").append(Util.getString(datoCaratulaFecuMap.get("DIRECTOR_7").getValor(), "")).append("<strong></strong></p></td>\n");
        html.append("          <td><p><strong>&nbsp;</strong></p></td>\n");
        html.append("          <td style=\"border:1px solid;\"><p style=\"font-size:10.0pt;mso-bidi-font-size:8.0pt;line-height:\n");
        html.append("115%;font-family:Arial\">").append(Util.getString(datoCaratulaFecuMap.get("RUT_DIRECTOR_7").getValor(), "")).append("<strong></strong></p></td>\n");
        html.append("        </tr>\n");
        html.append("        <tr>\n");
        html.append("          <td style=\"border:1px solid;\"><p style=\"font-size:10.0pt;mso-bidi-font-size:8.0pt;line-height:\n");
        html.append("115%;font-family:Arial\">").append(Util.getString(datoCaratulaFecuMap.get("DIRECTOR_8").getValor(), "")).append("</p></td>\n");
        html.append("          <td><p><strong>&nbsp;</strong></p></td>\n");
        html.append("          <td style=\"border:1px solid;\"><p style=\"font-size:10.0pt;mso-bidi-font-size:8.0pt;line-height:\n");
        html.append("115%;font-family:Arial\">").append(Util.getString(datoCaratulaFecuMap.get("RUT_DIRECTOR_8").getValor(), "")).append("<strong></strong></p></td>\n");
        html.append("        </tr> \n");
        html.append("        <tr>\n");
        html.append("           <td>&nbsp;</td>\n");
        html.append("            <td>&nbsp;</td>\n");
        html.append("            <td>&nbsp;</td>\n");
        html.append("        </tr>       \n");
        html.append("    </table></td>\n");
        html.append("  </tr>\n");
        html.append("</table>\n"); 
        html.append("</div>\n");
        html.append("</div>\n");
        System.err.println(html.toString());
        return html.toString();
    }

    public static void createPortada(WordprocessingMLPackage wordMLPackage, R run,
                                     Map<String, DatoCaratulaFecu> datoCaratulaFecuMap) throws JAXBException,
                                                                                               InvalidFormatException {
        AlternativeFormatInputPart afiPart = null;
        Relationship altChunkRel = null;
        CTAltChunk ac = null;
        afiPart = new AlternativeFormatInputPart(new PartName("/hw-caratula.html"));
        afiPart.setBinaryData(getPortadaFecuHtml(datoCaratulaFecuMap).getBytes());
        afiPart.setContentType(new ContentType("text/html"));
        altChunkRel = wordMLPackage.getMainDocumentPart().addTargetPart(afiPart);
        ac = Context.getWmlObjectFactory().createCTAltChunk();
        ac.setId(altChunkRel.getId());
        run.getContent().add(ac);
        wordMLPackage.getContentTypeManager().addDefaultContentType("html", "text/html");
    }

}
